CREATE TABLE Students(
    ID INT NOT NULL AUTO_INCREMENT,
    StudentCode VARCHAR(32) NOT NULL,
    Pass VARCHAR(32) NOT NULL,
    CONSTRAINT PRIMARY KEY(ID)
);

CREATE TABLE InfoStudent(
    ID INT NOT NULL AUTO_INCREMENT,
    StudentCode VARCHAR(32) NOT NULL,
    FullName VARCHAR(32) NOT NULL,
    Address VARCHAR(32) NOT NULL,
    Birthday VARCHAR(32) NOT NULL,
    SEX VARCHAR(32) NOT NULL,
    CONSTRAINT PRIMARY KEY(ID),
    CONSTRAINT FOREIGN KEY (StudentCode) REFERENCES students (StudentCode)
);